/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardResultsRouteImport } from './routes/dashboard.results'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardHomeworkRouteImport } from './routes/dashboard.homework'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardFeesRouteImport } from './routes/dashboard.fees'
import { Route as DashboardCreateParentRouteImport } from './routes/dashboard.create-parent'
import { Route as DashboardComplaintsRouteImport } from './routes/dashboard.complaints'
import { Route as DashboardClassesRouteImport } from './routes/dashboard.classes'
import { Route as DashboardCctvRouteImport } from './routes/dashboard.cctv'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeworkRoute = DashboardHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateParentRoute = DashboardCreateParentRouteImport.update({
  id: '/create-parent',
  path: '/create-parent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplaintsRoute = DashboardComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCctvRoute = DashboardCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/cctv': typeof DashboardCctvRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/create-parent': typeof DashboardCreateParentRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/homework': typeof DashboardHomeworkRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/cctv': typeof DashboardCctvRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/create-parent': typeof DashboardCreateParentRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/homework': typeof DashboardHomeworkRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/cctv': typeof DashboardCctvRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/create-parent': typeof DashboardCreateParentRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/homework': typeof DashboardHomeworkRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/chat'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/cctv'
    | '/dashboard/classes'
    | '/dashboard/complaints'
    | '/dashboard/create-parent'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/homework'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/cctv'
    | '/dashboard/classes'
    | '/dashboard/complaints'
    | '/dashboard/create-parent'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/homework'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/chat'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/cctv'
    | '/dashboard/classes'
    | '/dashboard/complaints'
    | '/dashboard/create-parent'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/homework'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/homework': {
      id: '/dashboard/homework'
      path: '/homework'
      fullPath: '/dashboard/homework'
      preLoaderRoute: typeof DashboardHomeworkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-parent': {
      id: '/dashboard/create-parent'
      path: '/create-parent'
      fullPath: '/dashboard/create-parent'
      preLoaderRoute: typeof DashboardCreateParentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/complaints': {
      id: '/dashboard/complaints'
      path: '/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof DashboardComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cctv': {
      id: '/dashboard/cctv'
      path: '/cctv'
      fullPath: '/dashboard/cctv'
      preLoaderRoute: typeof DashboardCctvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardCctvRoute: typeof DashboardCctvRoute
  DashboardClassesRoute: typeof DashboardClassesRoute
  DashboardComplaintsRoute: typeof DashboardComplaintsRoute
  DashboardCreateParentRoute: typeof DashboardCreateParentRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardHomeworkRoute: typeof DashboardHomeworkRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardCctvRoute: DashboardCctvRoute,
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardComplaintsRoute: DashboardComplaintsRoute,
  DashboardCreateParentRoute: DashboardCreateParentRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardHomeworkRoute: DashboardHomeworkRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
